### ISSUE TITLE
Suggestion: Change the color

### ISSUE THREAD

**Issue by devsubrata** [MyHub2023/GitHubTest#1]
I think it looks better if the main title is a bit more orange

The styling rule could be changed like this:
```css
h1 {
   color: #efa82e;
}
```
